_files:
    resource: "@LesPolypodesSimpleDMSBundle/Controller/FilesController.php"
    type:     annotation
    prefix:   /files

root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /files
        permanent: true