# To prevent strange issues, this route should be imported before your custom ones:
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /secure/connect

hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /secure/connect

hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /secure/connect

hwi_github_login:
    pattern: /secure/login/check-github

les_polypodes_simple_dms:
    resource: "@LesPolypodesSimpleDMSBundle/Resources/config/routing.yml"
