# To prevent strange issues, this route should be imported before your custom ones:
hwi_oauth_login:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix:   /login
hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect
hwi_oauth_connect:
    resource: "@HWIOAuthBundle/Resources/config/routing/connect.xml"
    prefix:   /connect

sedap_login:
    pattern: /login/check-sedap

les_polypodes_simple_dms:
    resource: "@LesPolypodesSimpleDMSBundle/Resources/config/routing.yml"
